// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import gorm "github.com/jinzhu/gorm"
import mock "github.com/stretchr/testify/mock"

// MenuInterface is an autogenerated mock type for the MenuInterface type
type MenuInterface struct {
	mock.Mock
}

// Contains provides a mock function with given fields: value
func (_m *MenuInterface) Contains(value string) bool {
	ret := _m.Called(value)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Menu provides a mock function with given fields: name, db
func (_m *MenuInterface) Menu(name string, db *gorm.DB) {
	_m.Called(name, db)
}
